pipeline{
    agent any
    stages{
        stage ('Newman test'){
            steps{
                bat '''
                cd api/newman
                node --version
                
                '''
            }

        }
    }



}