pipeline{
    agent any
    stages{
        stage ('Newman test'){
            steps{
                sh '''
                cd api/newman
                newman run TestsDeApi.postman_collection.json -e Heroku.postman_environment.json
                
                '''
            }

        }
        stage ('Jmeter test'){
            steps{
                sh '''
                cd load/jmeter
                jmeter -n -t examen_jmeter.jmx
                '''
            }
        }
    }



}